### ISSUE TITLE
Symsorter panics on parsing flags.

### ISSUE THREAD

**Issue by donalmacc** [getsentry/symbolicator#1215]
### Environment

Symsorter, running locally

### Steps to Reproduce

1. build symsorter with `cargo build`
2. run symsorter with RUST_BACKTRACE set , e.g. `RUST_BACKTRACE=1 symsorter -o output_path --prefix foo --bundlie-id bar --ignore-errors folder`

### Expected Result

Symsorter would run!

### Actual Result

Symsorter panics on startup with:

```
thread 'main' panicked at 'Mismatch between definition and access of `compression_level`. Could not downcast to TypeId { t: 1383475422167
2687376 }, need to downcast to TypeId { t: 13358953601680865708 }
', C:\Users\Donal\.cargo\registry\src\github.com-1ecc6299db9ec823\clap_builder-4.3.1\src\parser\error.rs:32:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: clap_builder::parser::error::MatchesError::unwrap
             at C:\Users\Donal\.cargo\registry\src\github.com-1ecc6299db9ec823\clap_builder-4.3.1\src\parser\error.rs:32
   3: clap_builder::parser::matches::arg_matches::ArgMatches::remove_one<usize>
             at C:\Users\Donal\.cargo\registry\src\github.com-1ecc6299db9ec823\clap_builder-4.3.1\src\parser\matches\arg_matches.rs:406
   4: symsorter::app::main
             at D:\Source\symbolicator\crates\symsorter\src\app.rs:340
   5: symsorter::main
             at D:\Source\symbolicator\crates\symsorter\src\main.rs:17
   6: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by donalmacc** [comment]
I created a PR for this https://github.com/getsentry/symbolicator/pull/1216 - I'm not much of a rust programmer but this seemed straightforward enough to fix.

**Comment by loewenheim** [comment]
Thank you very much for reporting & fixing!
