### ISSUE TITLE
[ERROR] sentry.errors.events: symbolicate.failed.infinite_retry

### ISSUE THREAD

**Issue by srtab** [getsentry/symbolicator#1423]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

25.0.4

### Docker Compose Version

2.24.7

### Steps to Reproduce

1. Install the Sentry Self Hosted with private DNS (indoors root CA);
2. Add reverse proxy for external traffic with public DNS;
3. Configure SDK for Angular application with `tracesSampleRate=1` and `browserTracingIntegration`;
4. Access application with SDK configured;

I don't know what is causing the problem, so i can't say if doing a similar configuration / steps, you will be able to reproduce.

### Expected Result

Don't see on `docker compose logs -f` being spammed with warning from symbolicator. 

```
....
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
....
```
And finish with:
```
worker-1  | 17:15:44 [ERROR] sentry.errors.events: symbolicate.failed.infinite_retry (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
```

### Actual Result

Here are the logs I'm obtaining every time an error is laucnhed from an Angular application:

```
....
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
worker-1  | 17:02:55 [WARNING] sentry.errors.events: symbolicate.slow (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
....
```
And finish with:
```
worker-1                                        | Traceback (most recent call last):
worker-1                                        |   File "/usr/local/lib/python3.11/site-packages/sentry/tasks/symbolication.py", line 268, in _do_symbolicate_event
worker-1                                        |     symbolicated_data = symbolication_function(symbolicator, data)
worker-1                                        |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1                                        |   File "/usr/local/lib/python3.11/site-packages/sentry/lang/javascript/processing.py", line 240, in process_js_stacktraces
worker-1                                        |     response = symbolicator.process_js(
worker-1                                        |                ^^^^^^^^^^^^^^^^^^^^^^^^
worker-1                                        |   File "/usr/local/lib/python3.11/site-packages/sentry/lang/native/symbolicator.py", line 215, in process_js
worker-1                                        |     return self._process("symbolicate_js_stacktraces", "symbolicate-js", json=json)
worker-1                                        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1                                        |   File "/usr/local/lib/python3.11/site-packages/sentry/lang/native/symbolicator.py", line 125, in _process
worker-1                                        |     self.on_request()
worker-1                                        |   File "/usr/local/lib/python3.11/site-packages/sentry/tasks/symbolication.py", line 244, in on_symbolicator_request
worker-1                                        |     raise SymbolicationTimeout
worker-1                                        | sentry.tasks.symbolication.SymbolicationTimeout
worker-1                                        | 17:41:42 [ERROR] sentry.errors.events: symbolicate.failed.infinite_retry (project_id=1 event_id='1b839edf67c94e1e95bf08505af7f669')
```

### Event ID

This is a self hosted problem, so i don't think that an event ID witll be helpfull here.

**Comment by Swatinem** [comment]
The warning being spewed multiple times a second is very suspect. it should only be triggered in an interval of a few seconds at most.
Also the soft and hard timeouts are quite high, so there might be a different misconfiguration issue, where symbolicator requests may be failing for some unknown reason.
Is symbolicator running properly? What does its output say?

Other than that, maybe the requests actually take such a long time to symbolicate. That could be possible because of unreasonably slow symbol servers. Do you have anything like that configured?

**Comment by srtab** [comment]
I'm pretty new on this. How can i confirm if symbolicator is running properly?

The only log i can found from symbolicator container is: 
```
symbolicator-1  | 2024-04-01T15:16:45.865898264Z  INFO symbolicator::server: Starting HTTP server on 0.0.0.0:3021
```
The configurations are the defaults, I've checked my projects and they have Microsoft and Nuget.org selected.

Does the symbolicator try to download / access files from the DNS where my application is being served?

**Comment by Swatinem** [comment]
Yes, Symbolicator does requests back to Sentry, if that is what you are asking.

And yes, as I see in your log, this is a `symbolicate_js_stacktraces` call, in which cases it might also scrape minified javascript and sourcemaps from the url mentioned in the stack trace.

**Comment by srtab** [comment]
@Swatinem Thanks for the help! I finally found the cause of my issue, and then I found another one.

1. I tried to communicate directly with `symbolicator` and got a 503. My installation is behind a proxy and when the worker tried to connect to `http//symbolicator:3021`, the request went to the proxy instead. I've configured the proxy as documented [here](https://develop.sentry.dev/self-hosted/#installing-behind-a-proxy), but the `symbolicator` is not referenced. After adding the `symbolicator` to the NO_PROXY config, the problem was finally fixed;
2. I also have Sentry installed with a custom CA and the Symbolicator does not seem to have the certificates folder mapped to volumes. Also, the `update-ca-cetificates' is not called on image startup.

**Comment by Swatinem** [comment]
> 2\. I also have Sentry installed with a custom CA and the Symbolicator does not seem to have the certificates folder mapped to volumes. Also, the `update-ca-cetificates' is not called on image startup.

I don’t think the Symbolicator -> Sentry call is using TLS by default, though it depends on the internal URL that is being used. (That Sentry sends to Symbolicator for callbacks)

We had some other similar requests recently with other customers running into problems with self-signed certificates. What would a solution look like that solves this problem for you?

**Comment by Swatinem** [comment]
Oh this makes sense.

There is actually a per-project setting to control this here:

![image](https://github.com/getsentry/symbolicator/assets/580492/b305235f-677e-4b0f-a9e9-b58d980c026f)

We actually never implemented this setting before when porting JavaScript processing to a new infrastructure.
Now we have implemented support for not checking TLS in symbolicator "in general", we would just have to hook this up so that it properly honors this project setting when scraping source maps.

---

That being said, usually one should upload sourcemaps directly so Sentry, so Symbolicator shouldn’t scrape those. But I guess this is reporting errors happening directly in the self-hosted Sentry UI to Sentry, so you are unlikely to have uploaded sourcemaps for that :-D

**Comment by loewenheim** [comment]
https://github.com/getsentry/symbolicator/pull/1435 addresses one half of this.

**Comment by loewenheim** [comment]
And https://github.com/getsentry/sentry/pull/68682 is the other half.

**Comment by loewenheim** [comment]
This should be fixed as of sentry 24.4.0.
