### ISSUE TITLE
Symbol server depricated, but new one is not yet ready.

### ISSUE THREAD

**Issue by mrPsycho** [getsentry/symbolicator#161]
Hello,

```
root@server:/opt/symbolserver# RUST_BACKTRACE=1 /usr/bin/cargo run -- --config=symbolserver.yml run
    Finished dev [unoptimized + debuginfo] target(s) in 0.90s
     Running `target/debug/sentry-symbolserver --config=symbolserver.yml run`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  10: openssl::ssl::SslContextBuilder::set_options
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.7/src/ssl/mod.rs:843
  11: openssl::ssl::connector::ctx
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.7/src/ssl/connector.rs:35
  12: openssl::ssl::connector::SslConnectorBuilder::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.7/src/ssl/connector.rs:52
  13: native_tls::imp::TlsConnector::builder
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.1.1/src/imp/openssl.rs:166
  14: native_tls::TlsConnector::builder
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.1.1/src/lib.rs:356
  15: hyper_native_tls::NativeTlsClient::new
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-native-tls-0.2.2/src/lib.rs:111
  16: libsymbolserver::s3::new_hyper_client
             at src/s3.rs:67
  17: libsymbolserver::s3::S3::from_config
             at src/s3.rs:90
  18: libsymbolserver::memdb::stash::MemDbStash::new
             at src/memdb/stash.rs:161
  19: libsymbolserver::api::server::ApiServer::new
             at src/api/server.rs:93
  20: libsymbolserver::cli::run_action
             at src/cli.rs:371
  21: libsymbolserver::cli::execute
             at src/cli.rs:277
  22: libsymbolserver::cli::main
             at src/cli.rs:80
  23: sentry_symbolserver::main
             at src/main.rs:4
  24: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  25: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  26: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  27: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  28: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  29: main
  30: __libc_start_main
  31: _start
```

can you please help me with old one server, which is kinda deprecated, but new one is not ready yet?

**Comment by untitaker** [comment]
This repository is for symbolicator, which we use now. Symbolserver is deprecated. Where do you see that Symbolicator is not ready?

**Comment by mrPsycho** [comment]
https://github.com/getsentry/symbolicator/issues/122

**Comment by flub** [comment]
i suspect there's little point keeping this open by now
