### ISSUE TITLE
[Panic] thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<proto::op::Query, dns_lru::LruValue>` uninitialized

### ISSUE THREAD

**Issue by uiopwang** [getsentry/symbolicator#281]
Start up sentry snuba relay symbolicator.
Trigger a crash in iOS client.
Get panic bellow.

```shell
RUST_BACKTRACE=full ./symbolicator run --config local.yml

## config file
cache_dir: "/data"
bind: "0.0.0.0:3021"
logging:
  level: "warn"
metrics:
  statsd: null
sentry_dsn: my_sentry_dsn_url
```

```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<proto::op::Query, dns_lru::LruValue>` uninitialized, which is invalid', /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:483:5
   1: core::panicking::panic_fmt
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/panicking.rs:85:14
   2: core::panicking::panic
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/panicking.rs:50:5
   3: core::mem::uninitialized
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/mem/mod.rs:659:9
   4: linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174:52
   5: linked_hash_map::LinkedHashMap<K,V,S>::insert
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304:9
   6: lru_cache::LruCache<K,V,S>::insert
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lru-cache-0.1.2/src/lib.rs:119:23
   7: trust_dns_resolver::dns_lru::DnsLru::insert
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.10.3/src/dns_lru.rs:168:9
   8: <trust_dns_resolver::lookup_state::InsertCache as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.10.3/src/lookup_state.rs:395:41
   9: <trust_dns_resolver::lookup_state::QueryState<C> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.10.3/src/lookup_state.rs:612:24
  10: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113:13
  11: futures::future::chain::Chain<A,B,C>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:26:23
  12: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/then.rs:32:9
  13: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113:13
  14: <trust_dns_resolver::lookup_ip::LookupIpFuture<C> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.10.3/src/lookup_ip.rs:94:25
  15: futures::future::chain::Chain<A,B,C>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/chain.rs:32:48
  16: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/and_then.rs:32:9
  17: <futures::future::either::Either<A,B> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/either.rs:35:37
  18: <trust_dns_resolver::async_resolver::Background<F,G> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-resolver-0.10.3/src/async_resolver/mod.rs:345:9
  19: <actix::actors::resolver::ResolveFut as actix::fut::ActorFuture>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/actors/resolver.rs:360:19
  20: actix::fut::chain::Chain<A,B,C>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/fut/chain.rs:38:49
  21: <actix::fut::and_then::AndThen<A,B,F> as actix::fut::ActorFuture>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/fut/and_then.rs:44:9
  22: <alloc::boxed::Box<F> as actix::fut::ActorFuture>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/fut/mod.rs:313:9
  23: actix::fut::chain::Chain<A,B,C>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/fut/chain.rs:38:49
  24: <alloc::boxed::Box<F> as actix::fut::ActorFuture>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/fut/mod.rs:313:9
  25: <actix::contextimpl::ContextFut<A,C> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/contextimpl.rs:355:23
  26: <actix::supervisor::Supervisor<A> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/supervisor.rs:147:19
  27: <alloc::boxed::Box<F> as futures::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/future/mod.rs:113:13
  28: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329:45
  29: futures::task_impl::Spawn<T>::enter::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399:27
  30: futures::task_impl::std::set
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/std/mod.rs:83:13
  31: futures::task_impl::Spawn<T>::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:399:9
  32: futures::task_impl::Spawn<T>::poll_fn_notify
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:291:9
  33: futures::task_impl::Spawn<T>::poll_future_notify
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.29/src/task_impl/mod.rs:329:9
  34: tokio_current_thread::scheduler::Scheduled<U>::tick
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/scheduler.rs:351:25
  35: tokio_current_thread::scheduler::Scheduler<U>::tick::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/scheduler.rs:330:47
  36: tokio_current_thread::Borrow<U>::enter::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:800:40
  37: tokio_current_thread::CurrentRunner::set_spawn
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:841:9
  38: tokio_current_thread::Borrow<U>::enter::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:800:13
  39: std::thread::local::LocalKey<T>::try_with
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/local.rs:272:16
  40: std::thread::local::LocalKey<T>::with
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/local.rs:248:9
  41: tokio_current_thread::Borrow<U>::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:798:9
  42: tokio_current_thread::scheduler::Scheduler<U>::tick
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/scheduler.rs:330:24
  43: tokio_current_thread::Entered<P>::tick
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:624:9
  44: tokio_current_thread::Entered<P>::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:514:13
  45: tokio::runtime::current_thread::runtime::Runtime::block_on::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:200:23
  46: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:241:25
  47: tokio_executor::global::with_default::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:221:9
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/local.rs:272:16
  49: std::thread::local::LocalKey<T>::with
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/thread/local.rs:248:9
  50: tokio_executor::global::with_default
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:190:5
  51: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:239:21
  52: tokio_timer::timer::handle::with_default
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/timer/handle.rs:74:5
  53: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:232:17
  54: tokio_timer::clock::clock::with_default
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/clock/clock.rs:125:5
  55: tokio::runtime::current_thread::runtime::Runtime::enter::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:231:13
  56: tokio_reactor::with_default
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/lib.rs:220:5
  57: tokio::runtime::current_thread::runtime::Runtime::enter
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:230:9
  58: tokio::runtime::current_thread::runtime::Runtime::block_on
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/current_thread/runtime.rs:198:9
  59: actix::system::SystemRunner::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.7.9/src/system.rs:174:26
  60: symbolicator::server::run
             at ./src/server.rs:38:5
  61: symbolicator::cli::execute
             at ./src/cli.rs:85:25
  62: symbolicator::main
             at ./src/main.rs:35:11
  63: core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
```

**Comment by flub** [comment]
Strange, this looks like an error from actix but we've not seen this in our production at all.  Is this entirely repeatable or only happened once?  Are you able to process any crash from the iOS client?  Could you also give some details about the host running symbolicator?

**Comment by uiopwang** [comment]
I use master code compile. Always get panic. 
```
commit 2dd4b36c82d2b39c589f73f9c21a4e9d5c6a4126
Author: Floris Bruynooghe <flub@sentry.io>
Date:   Wed Oct 28 14:37:37 2020 +0100

    ref(objects): Move object id comparison around (#278)

    ref(objects): Move object id comparison around

    Keep logical things a little closer together.
```

iOS crash code
```
- (void)forceCrash {
    NSArray *array = @[@1, @2];
    TLogD(@"%ld", (long)[array[4] integerValue]);
}
```

I switch code to tag 0.2.0 works fine now.

host info
```
Linux version 4.19.0-6.el7.ucloud.x86_64 (root@2d6b517b2939) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)) #1 SMP Wed Feb 12 07:32:16 UTC 2020
```

**Comment by flub** [comment]
> I switch code to tag 0.2.0 works fine now.

This is very interesting.  Any chance you could git bisect this further to find the commit that breaks things for you?

**Comment by uiopwang** [comment]
Sorry, we already in test now. It will block other guys work. Later, we may setup up an staging env.I can check it out then.

**Comment by mitsuhiko** [comment]
This is resolved on master by upgrading a dependency.
